#!/bin/bash

curl -LO https://github.com/stone-co/conta-stone-sdk-sample-ios/releases/download/0.1.0/ContaStoneFrameworks-swift-5.3.zip

unzip ContaStoneFrameworks-swift-5.3.zip

rm -rf ContaStoneFrameworks-swift-5.3.zip
rm -rf __MACOSX

pod install
